# Generated by Django 3.1.1 on 2020-09-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
                ('population', models.FloatField(default=0)),
                ('population_density', models.FloatField(default=0)),
                ('median_age', models.FloatField(default=0)),
                ('aged_65_older', models.FloatField(default=0)),
                ('aged_70_older', models.FloatField(default=0)),
                ('gdp_per_capita', models.FloatField(default=0)),
                ('cardiovasc_death_rate', models.FloatField(default=0)),
                ('diabetes_prevalence', models.FloatField(default=0)),
                ('handwashing_facilities', models.FloatField(default=0)),
                ('hospital_beds_per_thousand', models.FloatField(default=0)),
                ('life_expectancy', models.FloatField(default=0)),
                ('human_development_index', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('new_cases', models.FloatField(default=0)),
                ('total_cases', models.FloatField(default=0)),
                ('new_deaths', models.FloatField(default=0)),
                ('total_deaths', models.FloatField(default=0)),
                ('new_cases_per_million', models.FloatField(default=0)),
                ('total_cases_per_million', models.FloatField(default=0)),
                ('new_deaths_per_million', models.FloatField(default=0)),
                ('total_deaths_per_million', models.FloatField(default=0)),
                ('import_date', models.DateTimeField(verbose_name='import date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owid.country')),
            ],
        ),
    ]
