# VARIABLES

import main.secrets as secrets

APP_BASE = 'http://127.0.0.1:8000/snc'
#APP_BASE = 'http://pc.latidude99.com/snc'


GOOGLE_API_KEY_DEV_UN = secrets.GOOGLE_MAPS_JAVASCRIPT_API_KEY_DEV_UNRESTRICTED
GOOGLE_API_KEY_DEV = secrets.GOOGLE_MAPS_JAVASCRIPT_API_KEY_DEV
GOOGLE_API_KEY_PROD = secrets.GOOGLE_MAPS_JAVASCRIPT_API_KEY_PROD






